### ISSUE TITLE
Refactor React Flow not to load / execute same code again and again

### ISSUE THREAD

**Issue by sujin2f** [sujin2f/Sujin#28]
Fix too many repetition!

**Comment by sinharaksh1t** [comment]
Can you please elaborate a bit on this?

**Comment by sujin2f** [comment]
@sinharaksh1t This is basically the personal project for my personal website, so the issues are written simply I could remember. However, it's good to hear the interest from you. :D 

In the `dev/gutenberg` branch, I remake the front side of the theme with React which is provided WP's new editor Gutenberg. Yes. WP basically has React. It's almost done, but I want to adjust the event flow and state control not to load / execute same code again and again by React. This is the meaning of this ticket.

**Comment by sinharaksh1t** [comment]
Gotcha, thanks for the clarification. I was just going through some open issues on Github which are React projects. I just came across this and wanted to see if there is something I can contribute to here. No worries though, I will continue my search and commit to one of the tasks just to get some hands-on React experience and some open source contributions :D

**Comment by sujin2f** [comment]
Partially done by #37
